spring:
  application:
    name: api-user-e2e-test
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_log: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create

jwt:
  access-token:
    valid-time: 30m
    secret: end2eTestAccessTokenSecretQWERTYUIOP12345678900
  refresh-token:
    valid-time: 7d
    secret: end2eTestRefreshTokenSecretQWERTYUIOP1234567890
