spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        ddl-auto: create
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

storage:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    pool-name: core
    data-source-properties:
      rewriteBatchedStatements: true