name: Java CI with Gradle

on:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run e2eTest with Gradle
        run: ./gradlew e2eTest

      - name: Run unitTest with Gradle
        run: ./gradlew unitTest

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build Docker Image for api-user
        run: docker build -t api-user:latest -f ./api-user/Dockerfile ./api-user

      - name: Build Docker Image for api-admin (if necessary)
        run: |
          if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -qE '^api-admin/|^support/|^storage/|^build.gradle.kts$|^settings.gradle.kts$|^gradle.properties$'; then
            echo "Building Docker image for api-admin"
            docker build -t api-admin:latest -f ./api-admin/Dockerfile ./api-admin
          else
            echo "No relevant changes in api-admin or its dependencies; skipping Docker build"
          fi
