name: Java CI with Gradle

on:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Set up JDK 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run tests with Gradle(containing e2eTest, unitTest)
        run: ./gradlew test # --info # the option is for debugging

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build Docker Image for api-user
        run: docker build -t api-user:latest -f ./api-user/Dockerfile ./api-user

      - name: Build Docker Image for api-admin
        run: docker build -t api-admin:latest -f ./api-admin/Dockerfile ./api-admin
