name: Java CI with Gradle

on:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run e2eTest with Gradle
        run: ./gradlew e2eTest

      - name: Run unitTest with Gradle
        run: ./gradlew unitTest

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build Docker Image for api-user
        run: docker build -t api-user:latest -f ./api-user/Dockerfile ./api-user

      # Runs only when there are changes related to the api-admin module
      - name: Build Docker Image for api-admin
        if: |
          contains(github.event.pull_request.changed_files, 'api-admin/') ||
          contains(github.event.pull_request.changed_files, 'storage/') || 
          contains(github.event.pull_request.changed_files, 'support/') ||
          contains(github.event.pull_request.changed_files, '^build.gradle.kts$') ||
          contains(github.event.pull_request.changed_files, '^settings.gradle.kts$') ||
          contains(github.event.pull_request.changed_files, '^gradle.properties$')
        run: docker build -t api-admin:latest -f ./api-admin/Dockerfile ./api-admin
